server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

app:
  cors:
    allowed-origin: ${FRONTEND_ORIGIN:http://localhost:4200}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          audience: ${JWT_AUDIENCE}
          jwkSetUri: ${JWT_JWK_SET_URI}